Added logging of env variables

diff --git a/.github/workflows/firebase-hosting-merge.yml b/.github/workflows/firebase-hosting-merge.yml
--- a/.github/workflows/firebase-hosting-merge.yml
+++ b/.github/workflows/firebase-hosting-merge.yml
@@ -19,9 +19,23 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+
+      # Log environment variables to ensure they are loaded
+      - name: Check environment variables
+        run: |
+          echo "Checking environment variables..."
+          env_vars=(VITE_APP_API_KEY VITE_APP_AUTH_DOMAIN VITE_APP_PROJECT_ID VITE_APP_DATABASE_URL VITE_APP_STORAGE_BUCKET VITE_APP_MESSAGING_SENDER_ID VITE_APP_APP_ID)
+          for var in "${env_vars[@]}"; do
+            if [ -z "${!var}" ]; then
+              echo "ERROR: $var is not set or is empty."
+              exit 1
+            else
+              echo "$var is set."
+            fi
+          done
+
       - run: npm ci && npm run build
       - uses: FirebaseExtended/action-hosting-deploy@v0
-
         with:
           repoToken: ${{ secrets.GITHUB_TOKEN }}
           firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHADE_OPTIMIZER_95D28 }}
